# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Perforce Helix Core Actions
  # You may pin to the exact commit or the version.
  # uses: perforce/setup-p4@e10968a4d12316faa7a940be013dbe3283dd2ad8
  uses: perforce/setup-p4@1.0.2
  with:
    # p4 command to execute
    command: 
    # arguments for p4 cli that go before p4 command
    global_options: # optional
    # arguments for p4 cli that go after p4 command
    arguments: # optional
    # This is the P4 spec contents for the resource you are creating
    spec: # optional
    # Version of P4 binary to use.  When a step has this set it will download and install the P4 CLI.
    p4_version: # optional, default is 21.2
    # The working directory to use when running p4 commands.
    working_directory: # optional, default is .
